### ISSUE TITLE
TP6: me dá dos errores

### ISSUE THREAD

**Issue by jaarac** [CarlosValdezAlejandro/Vision-por-Computadora#1]
primer error:

ingrese angulo de traslación: 45
ingrese traslación en x: 20 
ingrese traslación en y: 20
ingrese valor de escala: 2.3
Traceback (most recent call last):
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP6/TP6.py", line 71, in <module>
    input_values()
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP6/TP6.py", line 42, in input_values
    scale=int(input('ingrese valor de escala: '))
ValueError: invalid literal for int() with base 10: '2.3'

La escala debería ser float.

-------------------------------------------------------------------
segundo error:

ingrese angulo de traslación: 45
ingrese traslación en x: 20
ingrese traslación en y: 20
ingrese valor de escala: 2
Traceback (most recent call last):
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP6/TP6.py", line 82, in <module>
    cv2.imwrite('lenna_crop_trans_sca.png', img_similarity)
NameError: name 'img_similarity' is not defined

**Comment by CarlosValdezAlejandro** [comment]
No encuentro esta definición en mi código, habrá habido confusion con el codigo?

        cv2.imwrite('lenna_crop_trans_sca.png', img_similarity)
        NameError: name 'img_similarity' is not defined

Ya cambié dos 'int' por 'float' en el código. No me percaté de eso. Gracias

**Comment by jaarac** [comment]
https://github.com/CarlosValdezAlejandro/Vision-por-Computadora/blob/549d98f9776a8b43b53a6e957fcbda4e1d2d6522/TP6/TP6.py#L82
