### ISSUE TITLE
TP7: error cuando apreto la "a"

### ISSUE THREAD

**Issue by jaarac** [CarlosValdezAlejandro/Vision-por-Computadora#2]
Cuando apreto la "a" se rompe  y me da este error: creo que tiene que ver con el nombre da las ventanas.

Traceback (most recent call last):
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP7/TP7.py", line 82, in <module>
    dst_coord = selected_points(img_point)
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP7/TP7.py", line 38, in selected_points
    cv2.setMouseCallback('Selección de tres (3) puntos', mouse_points)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-agffqapq/opencv/modules/highgui/src/window_QT.cpp:718: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

**Comment by CarlosValdezAlejandro** [comment]
Me funciona bien a mi. 
Estoy usando Anaconda, Jupyter Notebook.
De igual manera quité del nombre de la ventana los caracteres especiales por si llega a dar error por eso.
