### ISSUE TITLE
TP8: error cuando apreto la "h"

### ISSUE THREAD

**Issue by jaarac** [CarlosValdezAlejandro/Vision-por-Computadora#3]
Me dá el mismo error que el TP7:

Traceback (most recent call last):
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP8/TP8.py", line 84, in <module>
    src_coord = selected_points(img_point)
  File "/home/jaarac/docencia/utn/computer_vision/cvcordoba/frc/2021/repos/59845/TP8/TP8.py", line 40, in selected_points
    cv2.setMouseCallback('Selección de tres (4) puntos', mouse_points)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-agffqapq/opencv/modules/highgui/src/window_QT.cpp:718: error: (-27:Null pointer) NULL window handler in function 'cvSetMouseCallback'

**Comment by CarlosValdezAlejandro** [comment]
Lo mismo que el TP7, cambié los caracteres por si es eso. Me funciona bien a mi.
